#!/bin/sh

# Change to MyWRT upstream in every update

uci -q set amlogic.config.amlogic_firmware_repo='https://github.com/MyWRT/amlogic-s9xxx-openwrt'
uci -q set amlogic.config.amlogic_kernel_path='https://github.com/MyWRT/amlogic-s9xxx-kernel'
uci -q commit amlogic

exit 0
